<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required|max:255',
            'email' => 'required|max:255|email',
            'major_id' => 'required|exists:majors,id',
            'services_type_id' => 'required|exists:services_types,id',
            'phone' => 'required|max:255',
            'message' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'major_id.required' => helperTrans('web.the major is required'),
            'email.required' => helperTrans('web.the email is required'),
            'name.required' => helperTrans('web.the name is required'),
            'services_type_id.required' => helperTrans('web.the services type is required'),
            'phone.required' => helperTrans('web.the phone is required'),
            'message.required' => helperTrans('web.the message is required'),

        ]; // TODO: Change the autogenerated stub
    }
}
