<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequestsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required|max:500',
            'email' => 'required|max:500|email',
            'major_id' => 'required|exists:majors,id',
            'services_type_id' => 'required|exists:services_types,id',
            'date' => 'required|date|after:yesterday',
            'text' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'major_id.required' => helperTrans('web.the major is required'),
            'email.required' => helperTrans('web.the email is required'),
            'name.required' => helperTrans('web.the name is required'),
            'services_type_id.required' => helperTrans('web.the services type is required'),
            'date.required' => helperTrans('web.the date is required'),
            'text.required' => helperTrans('web.the text is required'),
            'date.after' => helperTrans('web.The date must start from today'),

        ]; // TODO: Change the autogenerated stub
    }
}
